using System.Collections.Generic;
using Codice.Client.Common.GameUI;
using Core.Detection.Audio;
using Core.Detection.Audio.DataStructures;
using Core.Equipment;
using Physics.Core.DataStructures;
using Physics.Core.PhysicsActors;
using Primitives.Items;
using Unity.Common.Unity;
using UnityEngine;

namespace Unity.Detection.Emitters
{
    public class GunSoundEmitter : MonoBehaviour, ISoundEmitter, IInitStats<EquipmentStats>
    {
        [SerializeField] private LayerMask _soundLayer;
        public Vector2 Origin => transform.position;
        public float MinRadius => _minRadius;
        private float _minRadius;

        private EquipmentStats _stats;
        private ContactFilter2D _filter;

        private void Awake()
        {
            _filter = new ContactFilter2D();
            _filter.SetLayerMask(_soundLayer);
            _filter.useLayerMask = true;
        }

        public void Init(EquipmentStats stats)
        {
            _stats = stats;
            Debug.Log($"Got stats: {stats}");
            _minRadius = _stats.SoundRadius;
        }
        public void EmitSound()
        {
            // Debug.Log($"MinRadius: {MinRadius}");
            float radius = MinRadius * 1f; // add in surface later this is just a test
            PingDetectors(new EmittedSound
            {
                Origin = transform.parent.position,
                Radius = radius,

            });
            DrawDebug(radius);
        }

        private void PingDetectors(EmittedSound sound)
        {
            // Get the detectors
            (int totalFound, List<Collider2D> detectors) = GetDetectors(sound);
            Debug.Log($"Found {totalFound} detectors");
            // Notify the detectors
            for (int i = 0; i < totalFound; i++)
            {
                ISoundDetector detector = detectors[i].GetComponentInChildren<ISoundDetector>();

                if (detector != null)
                {
                    Debug.Log($"Pinging {detectors[i].name}");
                    detector.Listen(sound);
                    DrawDebugCircle(detectors[i].transform.position, .5f, Color.purple);
                }
            }
        }
        private (int, List<Collider2D>) GetDetectors(EmittedSound sound)
        {
            List<Collider2D> detectors = new();
            int totalFound = Physics2D.OverlapCircle(sound.Origin, sound.Radius, _filter, detectors);
            return (totalFound, detectors);
        }

        private void DrawDebug(float soundRadius)
        {
            // Draw a circle based on the sound generated by the impact
            DrawDebugCircle(transform.position, soundRadius, Color.cyan);
        }

        private void DrawDebugCircle(Vector2 center, float radius, Color color, int segments = 32)
        {
            Debug.Log($"Drawing circle at {center} with radius {radius}");
            float angleStep = 360f / segments;
            Vector2 prevPoint = center + new Vector2(radius, 0);

            for (int i = 1; i <= segments; i++)
            {
                float angle = angleStep * i * Mathf.Deg2Rad;
                Vector2 nextPoint = center + new Vector2(Mathf.Cos(angle) * radius, Mathf.Sin(angle) * radius);
                Debug.DrawLine(prevPoint, nextPoint, color, .2f);
                prevPoint = nextPoint;
            }
        }

    }
}