using Core.Detection.Audio;
using Core.Physics.Collision.Callbacks;
using Core.Physics.Collisions;
using Physics.Core.DataStructures;
using Physics.Core.PhysicsActors;
using Primitives.Audio;
using UnityEngine;

namespace Unity.Equipment.Throwables
{
    public class ThrowableContactHandler : MonoBehaviour, ICollisionHandler, ICollisionEnterEvent, ISoundEmitter
    {
        private IPhysicsActor _actor;
        private ActorFrameData _frameData => _actor.Brain.FrameData;

        public Vector2 Origin { get; private set; }

        public float MinRadius => throw new System.NotImplementedException();

        private void Awake()
        {
            _actor = GetComponentInChildren<IPhysicsActor>();
        }
        public void OnCollisionEntered(CollisionInfo actor)
        {
            Debug.Log($"Got collision entered");
            Debug.Log(actor.CollisionPoint);
            Debug.Log(actor.Normal);
            Debug.Log(actor.Collider);
            Debug.Log(actor.OtherActor);
            Debug.Log(actor.Surface);
        }

        public SurfaceType GetSurface()
        {
            throw new System.NotImplementedException();
        }

        public float GetSpeed()
        {
            return _frameData.CurrentState.Velocity.magnitude;
        }

        public void EmitSound(float soundRadius)
        {
            DrawDebug();
        }

        private void DrawDebug()
        {
            // Draw a circle based on the sound generated by the impact
        }
    }
}